### ISSUE TITLE
Skulls Errors Out Due to null Profile Name

### ISSUE THREAD

**Issue by ItsSchatten** [Tweetzy/Skulls#22]
**Describe the bug**
Describe the bug in as much detail as possible, the more detailed, the chances of it being fixed is faster

Skulls are replaced with the default Steve skin.

```
[17:59:23 WARN]: java.lang.reflect.InvocationTargetException
[17:59:23 WARN]:        at jdk.internal.reflect.GeneratedConstructorAccessor119.newInstance(Unknown Source)
[17:59:23 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[17:59:23 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[17:59:23 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[17:59:23 WARN]:        at Skulls.jar//ca.tweetzy.skulls.flight.comp.NBTEditor.getHead(NBTEditor.java:456)
[17:59:23 WARN]:        at Skulls.jar//ca.tweetzy.skulls.flight.utils.QuickItem.createTexturedHead(QuickItem.java:444)
[17:59:23 WARN]:        at Skulls.jar//ca.tweetzy.skulls.flight.utils.QuickItem.of(QuickItem.java:371)
[17:59:23 WARN]:        at Skulls.jar//ca.tweetzy.skulls.impl.TexturedSkull.getItemStack(TexturedSkull.java:101)
[17:59:23 WARN]:        at Skulls.jar//ca.tweetzy.skulls.manager.SkullManager.getSkullItem(SkullManager.java:142)
[17:59:23 WARN]:        at Skulls.jar//ca.tweetzy.skulls.model.SkullItem.get(SkullItem.java:46)
[17:59:23 WARN]:        at Skulls.jar//ca.tweetzy.skulls.guis.MainGUI.draw(MainGUI.java:102)
[17:59:23 WARN]:        at Skulls.jar//ca.tweetzy.skulls.guis.MainGUI.<init>(MainGUI.java:50)
[17:59:23 WARN]:        at Skulls.jar//ca.tweetzy.skulls.commands.SkullsCommand.execute(SkullsCommand.java:58)
[17:59:23 WARN]:        at Skulls.jar//ca.tweetzy.skulls.flight.command.CommandManager.processRequirements(CommandManager.java:341)
[17:59:23 WARN]:        at Skulls.jar//ca.tweetzy.skulls.flight.command.CommandManager.onCommand(CommandManager.java:241)
[17:59:23 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[17:59:23 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[17:59:23 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServer.java:989)
[17:59:23 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[17:59:23 WARN]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265)
[17:59:23 WARN]:        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:330)
[17:59:23 WARN]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:314)
[17:59:23 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2207)
[17:59:23 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$19(PlayerConnection.java:2167)
[17:59:23 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[17:59:23 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[17:59:23 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[17:59:23 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[17:59:23 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[17:59:23 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1324)
[17:59:23 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193)
[17:59:23 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[17:59:23 WARN]:        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1301)
[17:59:23 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1294)
[17:59:23 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[17:59:23 WARN]:        at net.minecraft.server.MinecraftServer.u_(MinecraftServer.java:1272)
[17:59:23 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1160)
[17:59:23 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[17:59:23 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[17:59:23 WARN]: Caused by: java.lang.NullPointerException: Profile name must not be null
[17:59:23 WARN]:        at java.base/java.util.Objects.requireNonNull(Objects.java:233)
[17:59:23 WARN]:        at com.mojang.authlib.GameProfile.<init>(GameProfile.java:31)
[17:59:23 WARN]:        ... 39 more
```
**To Reproduce**
Describe how to reproduce this bug: EX.

1. Open the main menu

OR 

1. Open the search menu via the command.

**Expected behavior**

The plugin will properly display textured skulls.

**Screenshots**

![image](https://github.com/Tweetzy/Skulls/assets/15488581/67fa7af2-efdf-481b-b72b-e08f179ca674)

**Server Information (please complete the following information):**
- Provide the server version
- Provide the server jar (ex. paper/spigot)
- Plugin Version

This server is running Paper version git-Paper-207 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 38376f4)
You are running the latest version
Previous version: git-Paper-206 (MC: 1.20.2)

Plugin Version:
3.11.0

**Additional context**

**Comment by kiranhart** [comment]
Resolved in 3.11.1
