### ISSUE TITLE
table skulls_players already exists error

### ISSUE THREAD

**Issue by Swiftens** [Tweetzy/Skulls#47]
**Describe the bug**
Hi, I get this error every time I restart my server. I'm guessing it's because it tries to create a table that already exists in the database. It isn't that big of a deal since the plugin works fine. :) I think this can be fixed by changing the create queries to "CREATE IF NOT EXISTS TABLE..." 

**To Reproduce**
1. Upload plugin
2. Start Server
3. Restart Server (It then shows up after every restart)

**Server Information (please complete the following information):**
Server Version: 1.21.1
Server Jar: paper-1.21.1-77
Plugin Version: 3.18.1

**Additional Context:**
Here is the error I receive.
`[05:57:16 ERROR]: [Skulls] An error occurred executing an SQLite query: [SQLITE_ERROR] SQL error or missing database (table skulls_players already exists)
[05:57:16 WARN]: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (table skulls_players already exists)
[05:57:16 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1179)
[05:57:16 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1190)
[05:57:16 WARN]:        at org.sqlite.core.DB.throwex(DB.java:1150)
[05:57:16 WARN]:        at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
[05:57:16 WARN]:        at org.sqlite.core.NativeDB.prepare(NativeDB.java:132)
[05:57:16 WARN]:        at org.sqlite.core.DB.prepare(DB.java:264)
[05:57:16 WARN]:        at org.sqlite.jdbc3.JDBC3Statement.lambda$execute$0(JDBC3Statement.java:54)
[05:57:16 WARN]:        at org.sqlite.jdbc3.JDBC3Statement.withConnectionTimeout(JDBC3Statement.java:454)
[05:57:16 WARN]:        at org.sqlite.jdbc3.JDBC3Statement.execute(JDBC3Statement.java:43)
[05:57:16 WARN]:        at Skulls-3.18.1.jar//ca.tweetzy.skulls.database.migrations._1_InitialMigration.migrate(_1_InitialMigration.java:45)
[05:57:16 WARN]:        at Skulls-3.18.1.jar//ca.tweetzy.skulls.flight.database.DataMigrationManager.lambda$runMigrations$1(DataMigrationManager.java:97)
[05:57:16 WARN]:        at Skulls-3.18.1.jar//ca.tweetzy.skulls.flight.database.SQLiteConnector.connect(SQLiteConnector.java:76)
[05:57:16 WARN]:        at Skulls-3.18.1.jar//ca.tweetzy.skulls.flight.database.DataMigrationManager.runMigrations(DataMigrationManager.java:44)
[05:57:16 WARN]:        at Skulls-3.18.1.jar//ca.tweetzy.skulls.Skulls.onFlight(Skulls.java:99)
[05:57:16 WARN]:        at Skulls-3.18.1.jar//ca.tweetzy.skulls.flight.FlightPlugin.onEnable(FlightPlugin.java:91)
[05:57:16 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[05:57:16 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[05:57:16 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[05:57:16 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[05:57:16 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640)
[05:57:16 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589)
[05:57:16 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754)
[05:57:16 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516)
[05:57:16 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329)
[05:57:16 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215)
[05:57:16 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[05:57:16 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)`

**Comment by gaRt3n** [comment]
Can Vouch for this error:

Paper 1.21.1-82-master@1348e44

`[04:39:32 INFO]: [Skulls] Enabling Skulls v3.18.1
[04:39:32 INFO]:  
[04:39:32 INFO]: =============================
[04:39:32 INFO]: Skulls v3.18.1 by Tweetzy
[04:39:32 INFO]: Developer: Kiran Hart
[04:39:33 ERROR]: [Skulls] An error occurred executing an SQLite query: [SQLITE_ERROR] SQL error or missing database (table skulls_players already exists)
[04:39:33 WARN]: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (table skulls_players already exists)
[04:39:33 WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:1179)
[04:39:33 WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:1190)
[04:39:33 WARN]: 	at org.sqlite.core.DB.throwex(DB.java:1150)
[04:39:33 WARN]: 	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
[04:39:33 WARN]: 	at org.sqlite.core.NativeDB.prepare(NativeDB.java:132)
[04:39:33 WARN]: 	at org.sqlite.core.DB.prepare(DB.java:264)
[04:39:33 WARN]: 	at org.sqlite.jdbc3.JDBC3Statement.lambda$execute$0(JDBC3Statement.java:54)
[04:39:33 WARN]: 	at org.sqlite.jdbc3.JDBC3Statement.withConnectionTimeout(JDBC3Statement.java:454)
[04:39:33 WARN]: 	at org.sqlite.jdbc3.JDBC3Statement.execute(JDBC3Statement.java:43)
[04:39:33 WARN]: 	at Skulls-3.18.1.jar//ca.tweetzy.skulls.database.migrations._1_InitialMigration.migrate(_1_InitialMigration.java:45)
[04:39:33 WARN]: 	at Skulls-3.18.1.jar//ca.tweetzy.skulls.flight.database.DataMigrationManager.lambda$runMigrations$1(DataMigrationManager.java:97)
[04:39:33 WARN]: 	at Skulls-3.18.1.jar//ca.tweetzy.skulls.flight.database.SQLiteConnector.connect(SQLiteConnector.java:76)
[04:39:33 WARN]: 	at Skulls-3.18.1.jar//ca.tweetzy.skulls.flight.database.DataMigrationManager.runMigrations(DataMigrationManager.java:44)
[04:39:33 WARN]: 	at Skulls-3.18.1.jar//ca.tweetzy.skulls.Skulls.onFlight(Skulls.java:99)
[04:39:33 WARN]: 	at Skulls-3.18.1.jar//ca.tweetzy.skulls.flight.FlightPlugin.onEnable(FlightPlugin.java:91)
[04:39:33 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[04:39:33 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[04:39:33 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[04:39:33 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[04:39:33 WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640)
[04:39:33 WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589)
[04:39:33 WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754)
[04:39:33 WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516)
[04:39:33 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329)
[04:39:33 WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215)
[04:39:33 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[04:39:33 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)`
