### ISSUE TITLE
1.21.4

### ISSUE THREAD

**Issue by quiquelhappy** [Tweetzy/Skulls#55]
1.21.4 support, it currently throws the following error:
```
Could not pass event BlockPlaceEvent to Skulls v3.21.0
java.lang.NoClassDefFoundError: Could not initialize class ca.tweetzy.skulls.flight.nbtapi.NBTReflectionUtil
        at Skulls - v3.21.0.jar/ca.tweetzy.skulls.flight.nbtapi.NBTCompound.hasTag(NBTCompound.java:720) ~[Skulls - v3.21.0.jar:?]
        at Skulls - v3.21.0.jar/ca.tweetzy.skulls.listeners.SkullBlockListener.lambda$onSkullPlace$0(SkullBlockListener.java:55) ~[Skulls - v3.21.0.jar:?]
        at Skulls - v3.21.0.jar/ca.tweetzy.skulls.flight.nbtapi.NBT.get(NBT.java:106) ~[Skulls - v3.21.0.jar:?]
        at Skulls - v3.21.0.jar/ca.tweetzy.skulls.listeners.SkullBlockListener.onSkullPlace(SkullBlockListener.java:55) ~[Skulls - v3.21.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor263.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.4.jar:1.21.4-5-5403894]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.4.jar:1.21.4-5-5403894]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:458) ~[paper-1.21.4.jar:1.21.4-5-5403894]
        at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:498) ~[paper-1.21.4.jar:1.21.4-5-5403894]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:612) ~[paper-1.21.4.jar:1.21.4-5-5403894]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:2014) ~[paper-1.21.4.jar:1.21.4-5-5403894]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:44) ~[paper-1.21.4.jar:1.21.4-5-5403894]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:11) ~[paper-1.21.4.jar:1.21.4-5-5403894]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[paper-1.21.4.jar:1.21.4-5-5403894]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.4.jar:1.21.4-5-5403894]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:154) ~[paper-1.21.4.jar:1.21.4-5-5403894]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.4.jar:1.21.4-5-5403894]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1579) ~[paper-1.21.4.jar:1.21.4-5-5403894]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:207) ~[paper-1.21.4.jar:1.21.4-5-5403894]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:128) ~[paper-1.21.4.jar:1.21.4-5-5403894]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1556) ~[paper-1.21.4.jar:1.21.4-5-5403894]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1549) ~[paper-1.21.4.jar:1.21.4-5-5403894]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:138) ~[paper-1.21.4.jar:1.21.4-5-5403894]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1500) ~[paper-1.21.4.jar:1.21.4-5-5403894]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1510) ~[paper-1.21.4.jar:1.21.4-5-5403894]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1346) ~[paper-1.21.4.jar:1.21.4-5-5403894]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:341) ~[paper-1.21.4.jar:1.21.4-5-5403894]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NullPointerException [in thread "Server thread"]
        at java.base/java.util.ImmutableCollections$MapN.probe(Unknown Source) ~[?:?]
        at java.base/java.util.ImmutableCollections$MapN.get(Unknown Source) ~[?:?]
        at java.base/java.util.ImmutableCollections$AbstractImmutableMap.getOrDefault(Unknown Source) ~[?:?]
        at io.papermc.paper.pluginremap.reflect.PaperReflection.mapDeclaredFieldName(PaperReflection.java:79) ~[paper-1.21.4.jar:1.21.4-5-5403894]
        at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.getDeclaredField(AbstractDefaultRulesReflectionProxy.java:90) ~[reflection-rewriter-runtime-0.0.3.jar:?]
        at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.getDeclaredField(Unknown Source) ~[paper-1.21.4.jar:1.21.4-5-5403894]
        at Skulls - v3.21.0.jar/ca.tweetzy.skulls.flight.nbtapi.NBTReflectionUtil.<clinit>(NBTReflectionUtil.java:59) ~[Skulls - v3.21.0.jar:?]
        at Skulls - v3.21.0.jar/ca.tweetzy.skulls.flight.nbtapi.NBTCompound.hasTag(NBTCompound.java:720) ~[Skulls - v3.21.0.jar:?]
        at Skulls - v3.21.0.jar/ca.tweetzy.skulls.listeners.SkullBlockListener.lambda$onSkullPlace$0(SkullBlockListener.java:55) ~[Skulls - v3.21.0.jar:?]
        at Skulls - v3.21.0.jar/ca.tweetzy.skulls.flight.nbtapi.NBT.get(NBT.java:106) ~[Skulls - v3.21.0.jar:?]
        at Skulls - v3.21.0.jar/ca.tweetzy.skulls.listeners.SkullBlockListener.onSkullPlace(SkullBlockListener.java:55) ~[Skulls - v3.21.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor263.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.4.jar:1.21.4-5-5403894]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.4.jar:1.21.4-5-5403894]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:458) ~[paper-1.21.4.jar:1.21.4-5-5403894]
        at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:498) ~[paper-1.21.4.jar:1.21.4-5-5403894]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:612) ~[paper-1.21.4.jar:1.21.4-5-5403894]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:2014) ~[paper-1.21.4.jar:1.21.4-5-5403894]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:44) ~[paper-1.21.4.jar:1.21.4-5-5403894]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:11) ~[paper-1.21.4.jar:1.21.4-5-5403894]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[paper-1.21.4.jar:1.21.4-5-5403894]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.4.jar:1.21.4-5-5403894]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:154) ~[paper-1.21.4.jar:1.21.4-5-5403894]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.4.jar:1.21.4-5-5403894]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1579) ~[paper-1.21.4.jar:1.21.4-5-5403894]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:207) ~[paper-1.21.4.jar:1.21.4-5-5403894]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:128) ~[paper-1.21.4.jar:1.21.4-5-5403894]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1556) ~[paper-1.21.4.jar:1.21.4-5-5403894]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1549) ~[paper-1.21.4.jar:1.21.4-5-5403894]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:117) ~[paper-1.21.4.jar:1.21.4-5-5403894]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1506) ~[paper-1.21.4.jar:1.21.4-5-5403894]
        ... 3 more
```

**Comment by kiranhart** [comment]
He hasn't released it on the maven repo yet

**Comment by quiquelhappy** [comment]
why not just use jitpack
